### ISSUE TITLE
Midterm Exam Checklist

### ISSUE THREAD

**Issue by helvitiis** [dorothealint/Rick-and-Morty#7]
Copying the midterm exam guidelines for convenience here!

- [x] **Schema Design:** Design clear and well-documented schemas in Relax NG to guide and manage the team's markup for your project.

- [x] **XML Markup:** Complete a substantial amount of XML coding (this to be determined within your project teams, but prepare a solid foundation.) Check and correct this code with help from your project schema.

- [ ] You should feature some use of **regular expressions** (whether in up-conversion to XML, or in some kind of regular pattern matching) in your midterm project work.

- [x] **Website Development:** Produce some new substantial pages on your team's website, indicating what you are accomplishing and what you aim to produce by the end of the semester. If you can, you may provide some data drawn from XQuery on your project. 

    - [ ] Load your project files into your project directories on our eXist-db, write XQuery over them to extract some interesting data to survey (make a table or list, maybe a network? ) See if you can build the outputs into your website.

**Comment by dorothealint** [comment]
@quantum-satire I pushed a schema (well a start to one) with some of the ideas of things I want to tag.  I know it's going to have to be changed but I wanted to get one up here!
